### ISSUE TITLE
There's no way to install this in windows

### ISSUE THREAD

**Issue by ghost** [adamhenson/lighterbox#3]
There's no way to install this in windows, but it is advertised as working in windows on: 

https://techadminlab.com/best-brightness-control-software-for-windows-10/

I get it.  I'm not a programmer and don't know how to install software without an executable.  It isn't my life, and your software won't be very popular if you assume everyone knows what to do with a bunch of seemingly random files.  I fucking hate github.

**Comment by adamhenson** [comment]
This issue seems incorrectly opened in the `lighterbox` project. @ghost - this project is not related to the link you posted. Also, this issue is not understandable as you did not provide details.
